### ISSUE TITLE
Ruby Gems 上的版本有问题

### ISSUE THREAD

**Issue by 42thcoder** [hzlu/umeng_msg#4]
https://rubygems.org/gems/umeng_msg

0.2.0 版本的代码是错的, github 上的代码正常.

`umeng_msg-0.2.0/lib/umeng_msg/subject.rb:18`

```
    def push
      post_youmeng(CANCEL_URL, Params.push_params(@platform, @options))
    end

```

**Comment by hzlu** [comment]
@42thcoder 已经重新推了版本 0.2.1 上去了，抱歉，这个项目太久没维护了。
